name: d4_accessibility

channels:
  - esri
  - conda-forge

dependencies:
  - cookiecutter
  - jupyterlab
  - nodejs
  - pip
  - python=3.7
  - python-dotenv
  - geopandas
  - pandas
  - rasterio
  - appdirs
  - yaml
  - scipy
  - pyyaml
  - tqdm
  - osmnx
  - openpyxl
  - pyshp
  - pip:
    - boto3
    - -e ../../packages/emma
    - -e ../../packages/algi
    - -e ../../packages/rputils
